/**
 * The app's icon set: Phosphor (phosphoricons.com), one module per icon so
 * only these reach the bundle. The SSR builds need no context provider, so
 * they work in server and client components alike.
 *
 * Every icon goes through `decorative()`, which keeps two defaults the app
 * relied on: a 24px size when no size class is given, and aria-hidden unless
 * the icon carries its own label, so screen readers skip decorative glyphs
 * but still announce the few that stand alone ("AI analyzed").
 *
 * AI features deliberately avoid sparkle, robot and brain glyphs; they use
 * what the feature does instead (a lightbulb for insight, a calendar for
 * planning).
 */
import { forwardRef } from "react";
import type { Icon, IconProps } from "@phosphor-icons/react";
import { ArchiveIcon as ArchiveGlyph } from "@phosphor-icons/react/dist/ssr/Archive";
import { ArrowClockwiseIcon as ArrowClockwiseGlyph } from "@phosphor-icons/react/dist/ssr/ArrowClockwise";
import { ArrowCounterClockwiseIcon as ArrowCounterClockwiseGlyph } from "@phosphor-icons/react/dist/ssr/ArrowCounterClockwise";
import { ArrowLeftIcon as ArrowLeftGlyph } from "@phosphor-icons/react/dist/ssr/ArrowLeft";
import { ArrowRightIcon as ArrowRightGlyph } from "@phosphor-icons/react/dist/ssr/ArrowRight";
import { ArrowSquareOutIcon as ArrowSquareOutGlyph } from "@phosphor-icons/react/dist/ssr/ArrowSquareOut";
import { ArrowUUpLeftIcon as ArrowUUpLeftGlyph } from "@phosphor-icons/react/dist/ssr/ArrowUUpLeft";
import { ArrowUpIcon as ArrowUpGlyph } from "@phosphor-icons/react/dist/ssr/ArrowUp";
import { ArrowUpRightIcon as ArrowUpRightGlyph } from "@phosphor-icons/react/dist/ssr/ArrowUpRight";
import { ArrowsDownUpIcon as ArrowsDownUpGlyph } from "@phosphor-icons/react/dist/ssr/ArrowsDownUp";
import { AtomIcon as AtomGlyph } from "@phosphor-icons/react/dist/ssr/Atom";
import { BankIcon as BankGlyph } from "@phosphor-icons/react/dist/ssr/Bank";
import { BellIcon as BellGlyph } from "@phosphor-icons/react/dist/ssr/Bell";
import { BookBookmarkIcon as BookBookmarkGlyph } from "@phosphor-icons/react/dist/ssr/BookBookmark";
import { BookOpenIcon as BookOpenGlyph } from "@phosphor-icons/react/dist/ssr/BookOpen";
import { BookOpenTextIcon as BookOpenTextGlyph } from "@phosphor-icons/react/dist/ssr/BookOpenText";
import { BriefcaseIcon as BriefcaseGlyph } from "@phosphor-icons/react/dist/ssr/Briefcase";
import { BuildingsIcon as BuildingsGlyph } from "@phosphor-icons/react/dist/ssr/Buildings";
import { CalendarBlankIcon as CalendarBlankGlyph } from "@phosphor-icons/react/dist/ssr/CalendarBlank";
import { CalendarCheckIcon as CalendarCheckGlyph } from "@phosphor-icons/react/dist/ssr/CalendarCheck";
import { CalendarDotsIcon as CalendarDotsGlyph } from "@phosphor-icons/react/dist/ssr/CalendarDots";
import { CaretDownIcon as CaretDownGlyph } from "@phosphor-icons/react/dist/ssr/CaretDown";
import { CaretLeftIcon as CaretLeftGlyph } from "@phosphor-icons/react/dist/ssr/CaretLeft";
import { CaretRightIcon as CaretRightGlyph } from "@phosphor-icons/react/dist/ssr/CaretRight";
import { ChalkboardTeacherIcon as ChalkboardTeacherGlyph } from "@phosphor-icons/react/dist/ssr/ChalkboardTeacher";
import { ChatTextIcon as ChatTextGlyph } from "@phosphor-icons/react/dist/ssr/ChatText";
import { ChatsCircleIcon as ChatsCircleGlyph } from "@phosphor-icons/react/dist/ssr/ChatsCircle";
import { CheckIcon as CheckGlyph } from "@phosphor-icons/react/dist/ssr/Check";
import { CheckCircleIcon as CheckCircleGlyph } from "@phosphor-icons/react/dist/ssr/CheckCircle";
import { CheckSquareIcon as CheckSquareGlyph } from "@phosphor-icons/react/dist/ssr/CheckSquare";
import { ChecksIcon as ChecksGlyph } from "@phosphor-icons/react/dist/ssr/Checks";
import { CircleIcon as CircleGlyph } from "@phosphor-icons/react/dist/ssr/Circle";
import { CircleNotchIcon as CircleNotchGlyph } from "@phosphor-icons/react/dist/ssr/CircleNotch";
import { ClockIcon as ClockGlyph } from "@phosphor-icons/react/dist/ssr/Clock";
import { CodeIcon as CodeGlyph } from "@phosphor-icons/react/dist/ssr/Code";
import { CompassIcon as CompassGlyph } from "@phosphor-icons/react/dist/ssr/Compass";
import { CpuIcon as CpuGlyph } from "@phosphor-icons/react/dist/ssr/Cpu";
import { DatabaseIcon as DatabaseGlyph } from "@phosphor-icons/react/dist/ssr/Database";
import { DotsThreeIcon as DotsThreeGlyph } from "@phosphor-icons/react/dist/ssr/DotsThree";
import { DownloadSimpleIcon as DownloadSimpleGlyph } from "@phosphor-icons/react/dist/ssr/DownloadSimple";
import { EnvelopeSimpleIcon as EnvelopeSimpleGlyph } from "@phosphor-icons/react/dist/ssr/EnvelopeSimple";
import { FileArrowUpIcon as FileArrowUpGlyph } from "@phosphor-icons/react/dist/ssr/FileArrowUp";
import { FileMagnifyingGlassIcon as FileMagnifyingGlassGlyph } from "@phosphor-icons/react/dist/ssr/FileMagnifyingGlass";
import { FileTextIcon as FileTextGlyph } from "@phosphor-icons/react/dist/ssr/FileText";
import { FlameIcon as FlameGlyph } from "@phosphor-icons/react/dist/ssr/Flame";
import { FlaskIcon as FlaskGlyph } from "@phosphor-icons/react/dist/ssr/Flask";
import { FloppyDiskIcon as FloppyDiskGlyph } from "@phosphor-icons/react/dist/ssr/FloppyDisk";
import { FolderOpenIcon as FolderOpenGlyph } from "@phosphor-icons/react/dist/ssr/FolderOpen";
import { GearSixIcon as GearSixGlyph } from "@phosphor-icons/react/dist/ssr/GearSix";
import { GlobeIcon as GlobeGlyph } from "@phosphor-icons/react/dist/ssr/Globe";
import { GraduationCapIcon as GraduationCapGlyph } from "@phosphor-icons/react/dist/ssr/GraduationCap";
import { InfoIcon as InfoGlyph } from "@phosphor-icons/react/dist/ssr/Info";
import { KanbanIcon as KanbanGlyph } from "@phosphor-icons/react/dist/ssr/Kanban";
import { KeyIcon as KeyGlyph } from "@phosphor-icons/react/dist/ssr/Key";
import { KeyboardIcon as KeyboardGlyph } from "@phosphor-icons/react/dist/ssr/Keyboard";
import { LightbulbIcon as LightbulbGlyph } from "@phosphor-icons/react/dist/ssr/Lightbulb";
import { LinkSimpleIcon as LinkSimpleGlyph } from "@phosphor-icons/react/dist/ssr/LinkSimple";
import { ListIcon as ListGlyph } from "@phosphor-icons/react/dist/ssr/List";
import { ListChecksIcon as ListChecksGlyph } from "@phosphor-icons/react/dist/ssr/ListChecks";
import { ListPlusIcon as ListPlusGlyph } from "@phosphor-icons/react/dist/ssr/ListPlus";
import { MagnifyingGlassIcon as MagnifyingGlassGlyph } from "@phosphor-icons/react/dist/ssr/MagnifyingGlass";
import { MathOperationsIcon as MathOperationsGlyph } from "@phosphor-icons/react/dist/ssr/MathOperations";
import { MegaphoneIcon as MegaphoneGlyph } from "@phosphor-icons/react/dist/ssr/Megaphone";
import { MonitorIcon as MonitorGlyph } from "@phosphor-icons/react/dist/ssr/Monitor";
import { MoonIcon as MoonGlyph } from "@phosphor-icons/react/dist/ssr/Moon";
import { NoteIcon as NoteGlyph } from "@phosphor-icons/react/dist/ssr/Note";
import { NotePencilIcon as NotePencilGlyph } from "@phosphor-icons/react/dist/ssr/NotePencil";
import { PaletteIcon as PaletteGlyph } from "@phosphor-icons/react/dist/ssr/Palette";
import { PenNibIcon as PenNibGlyph } from "@phosphor-icons/react/dist/ssr/PenNib";
import { PencilSimpleIcon as PencilSimpleGlyph } from "@phosphor-icons/react/dist/ssr/PencilSimple";
import { PlugIcon as PlugGlyph } from "@phosphor-icons/react/dist/ssr/Plug";
import { PlugsIcon as PlugsGlyph } from "@phosphor-icons/react/dist/ssr/Plugs";
import { PlusIcon as PlusGlyph } from "@phosphor-icons/react/dist/ssr/Plus";
import { PulseIcon as PulseGlyph } from "@phosphor-icons/react/dist/ssr/Pulse";
import { PushPinIcon as PushPinGlyph } from "@phosphor-icons/react/dist/ssr/PushPin";
import { PushPinSlashIcon as PushPinSlashGlyph } from "@phosphor-icons/react/dist/ssr/PushPinSlash";
import { QuestionIcon as QuestionGlyph } from "@phosphor-icons/react/dist/ssr/Question";
import { ShieldCheckIcon as ShieldCheckGlyph } from "@phosphor-icons/react/dist/ssr/ShieldCheck";
import { ShuffleIcon as ShuffleGlyph } from "@phosphor-icons/react/dist/ssr/Shuffle";
import { SignOutIcon as SignOutGlyph } from "@phosphor-icons/react/dist/ssr/SignOut";
import { SlidersHorizontalIcon as SlidersHorizontalGlyph } from "@phosphor-icons/react/dist/ssr/SlidersHorizontal";
import { SquareIcon as SquareGlyph } from "@phosphor-icons/react/dist/ssr/Square";
import { SquaresFourIcon as SquaresFourGlyph } from "@phosphor-icons/react/dist/ssr/SquaresFour";
import { StackIcon as StackGlyph } from "@phosphor-icons/react/dist/ssr/Stack";
import { SunIcon as SunGlyph } from "@phosphor-icons/react/dist/ssr/Sun";
import { TargetIcon as TargetGlyph } from "@phosphor-icons/react/dist/ssr/Target";
import { TrashIcon as TrashGlyph } from "@phosphor-icons/react/dist/ssr/Trash";
import { UploadSimpleIcon as UploadSimpleGlyph } from "@phosphor-icons/react/dist/ssr/UploadSimple";
import { UserIcon as UserGlyph } from "@phosphor-icons/react/dist/ssr/User";
import { UsersIcon as UsersGlyph } from "@phosphor-icons/react/dist/ssr/Users";
import { WarningIcon as WarningGlyph } from "@phosphor-icons/react/dist/ssr/Warning";
import { XIcon as XGlyph } from "@phosphor-icons/react/dist/ssr/X";
import { XCircleIcon as XCircleGlyph } from "@phosphor-icons/react/dist/ssr/XCircle";
import { ArticleIcon as ArticleGlyph } from "@phosphor-icons/react/dist/ssr/Article";
import { CalendarPlusIcon as CalendarPlusGlyph } from "@phosphor-icons/react/dist/ssr/CalendarPlus";
import { ClipboardTextIcon as ClipboardTextGlyph } from "@phosphor-icons/react/dist/ssr/ClipboardText";
import { ExamIcon as ExamGlyph } from "@phosphor-icons/react/dist/ssr/Exam";
import { ListMagnifyingGlassIcon as ListMagnifyingGlassGlyph } from "@phosphor-icons/react/dist/ssr/ListMagnifyingGlass";
import { QuotesIcon as QuotesGlyph } from "@phosphor-icons/react/dist/ssr/Quotes";
import { StudentIcon as StudentGlyph } from "@phosphor-icons/react/dist/ssr/Student";

export type AppIcon = Icon;
export type AppIconProps = IconProps;

function decorative(Glyph: Icon, displayName: string): Icon {
  const Wrapped = forwardRef<SVGSVGElement, IconProps>(function AppIconImpl(props, ref) {
    const labelled = props["aria-label"] != null || props["aria-labelledby"] != null || props.alt != null;
    return <Glyph ref={ref} size={24} aria-hidden={labelled ? undefined : true} {...props} />;
  });
  Wrapped.displayName = displayName;
  return Wrapped;
}

export const ArchiveIcon = decorative(ArchiveGlyph, "ArchiveIcon");
export const ArrowClockwiseIcon = decorative(ArrowClockwiseGlyph, "ArrowClockwiseIcon");
export const ArrowCounterClockwiseIcon = decorative(ArrowCounterClockwiseGlyph, "ArrowCounterClockwiseIcon");
export const ArrowLeftIcon = decorative(ArrowLeftGlyph, "ArrowLeftIcon");
export const ArrowRightIcon = decorative(ArrowRightGlyph, "ArrowRightIcon");
export const ArrowSquareOutIcon = decorative(ArrowSquareOutGlyph, "ArrowSquareOutIcon");
export const ArrowUUpLeftIcon = decorative(ArrowUUpLeftGlyph, "ArrowUUpLeftIcon");
export const ArrowUpIcon = decorative(ArrowUpGlyph, "ArrowUpIcon");
export const ArrowUpRightIcon = decorative(ArrowUpRightGlyph, "ArrowUpRightIcon");
export const ArrowsDownUpIcon = decorative(ArrowsDownUpGlyph, "ArrowsDownUpIcon");
export const AtomIcon = decorative(AtomGlyph, "AtomIcon");
export const BankIcon = decorative(BankGlyph, "BankIcon");
export const BellIcon = decorative(BellGlyph, "BellIcon");
export const BookBookmarkIcon = decorative(BookBookmarkGlyph, "BookBookmarkIcon");
export const BookOpenIcon = decorative(BookOpenGlyph, "BookOpenIcon");
export const BookOpenTextIcon = decorative(BookOpenTextGlyph, "BookOpenTextIcon");
export const BriefcaseIcon = decorative(BriefcaseGlyph, "BriefcaseIcon");
export const BuildingsIcon = decorative(BuildingsGlyph, "BuildingsIcon");
export const CalendarBlankIcon = decorative(CalendarBlankGlyph, "CalendarBlankIcon");
export const CalendarCheckIcon = decorative(CalendarCheckGlyph, "CalendarCheckIcon");
export const CalendarDotsIcon = decorative(CalendarDotsGlyph, "CalendarDotsIcon");
export const CaretDownIcon = decorative(CaretDownGlyph, "CaretDownIcon");
export const CaretLeftIcon = decorative(CaretLeftGlyph, "CaretLeftIcon");
export const CaretRightIcon = decorative(CaretRightGlyph, "CaretRightIcon");
export const ChalkboardTeacherIcon = decorative(ChalkboardTeacherGlyph, "ChalkboardTeacherIcon");
export const ChatTextIcon = decorative(ChatTextGlyph, "ChatTextIcon");
export const ChatsCircleIcon = decorative(ChatsCircleGlyph, "ChatsCircleIcon");
export const CheckIcon = decorative(CheckGlyph, "CheckIcon");
export const CheckCircleIcon = decorative(CheckCircleGlyph, "CheckCircleIcon");
export const CheckSquareIcon = decorative(CheckSquareGlyph, "CheckSquareIcon");
export const ChecksIcon = decorative(ChecksGlyph, "ChecksIcon");
export const CircleIcon = decorative(CircleGlyph, "CircleIcon");
export const CircleNotchIcon = decorative(CircleNotchGlyph, "CircleNotchIcon");
export const ClockIcon = decorative(ClockGlyph, "ClockIcon");
export const CodeIcon = decorative(CodeGlyph, "CodeIcon");
export const CompassIcon = decorative(CompassGlyph, "CompassIcon");
export const CpuIcon = decorative(CpuGlyph, "CpuIcon");
export const DatabaseIcon = decorative(DatabaseGlyph, "DatabaseIcon");
export const DotsThreeIcon = decorative(DotsThreeGlyph, "DotsThreeIcon");
export const DownloadSimpleIcon = decorative(DownloadSimpleGlyph, "DownloadSimpleIcon");
export const EnvelopeSimpleIcon = decorative(EnvelopeSimpleGlyph, "EnvelopeSimpleIcon");
export const FileArrowUpIcon = decorative(FileArrowUpGlyph, "FileArrowUpIcon");
export const FileMagnifyingGlassIcon = decorative(FileMagnifyingGlassGlyph, "FileMagnifyingGlassIcon");
export const FileTextIcon = decorative(FileTextGlyph, "FileTextIcon");
export const FlameIcon = decorative(FlameGlyph, "FlameIcon");
export const FlaskIcon = decorative(FlaskGlyph, "FlaskIcon");
export const FloppyDiskIcon = decorative(FloppyDiskGlyph, "FloppyDiskIcon");
export const FolderOpenIcon = decorative(FolderOpenGlyph, "FolderOpenIcon");
export const GearSixIcon = decorative(GearSixGlyph, "GearSixIcon");
export const GlobeIcon = decorative(GlobeGlyph, "GlobeIcon");
export const GraduationCapIcon = decorative(GraduationCapGlyph, "GraduationCapIcon");
export const InfoIcon = decorative(InfoGlyph, "InfoIcon");
export const KanbanIcon = decorative(KanbanGlyph, "KanbanIcon");
export const KeyIcon = decorative(KeyGlyph, "KeyIcon");
export const KeyboardIcon = decorative(KeyboardGlyph, "KeyboardIcon");
export const LightbulbIcon = decorative(LightbulbGlyph, "LightbulbIcon");
export const LinkSimpleIcon = decorative(LinkSimpleGlyph, "LinkSimpleIcon");
export const ListIcon = decorative(ListGlyph, "ListIcon");
export const ListChecksIcon = decorative(ListChecksGlyph, "ListChecksIcon");
export const ListPlusIcon = decorative(ListPlusGlyph, "ListPlusIcon");
export const MagnifyingGlassIcon = decorative(MagnifyingGlassGlyph, "MagnifyingGlassIcon");
export const MathOperationsIcon = decorative(MathOperationsGlyph, "MathOperationsIcon");
export const MegaphoneIcon = decorative(MegaphoneGlyph, "MegaphoneIcon");
export const MonitorIcon = decorative(MonitorGlyph, "MonitorIcon");
export const MoonIcon = decorative(MoonGlyph, "MoonIcon");
export const NoteIcon = decorative(NoteGlyph, "NoteIcon");
export const NotePencilIcon = decorative(NotePencilGlyph, "NotePencilIcon");
export const PaletteIcon = decorative(PaletteGlyph, "PaletteIcon");
export const PenNibIcon = decorative(PenNibGlyph, "PenNibIcon");
export const PencilSimpleIcon = decorative(PencilSimpleGlyph, "PencilSimpleIcon");
export const PlugIcon = decorative(PlugGlyph, "PlugIcon");
export const PlugsIcon = decorative(PlugsGlyph, "PlugsIcon");
export const PlusIcon = decorative(PlusGlyph, "PlusIcon");
export const PulseIcon = decorative(PulseGlyph, "PulseIcon");
export const PushPinIcon = decorative(PushPinGlyph, "PushPinIcon");
export const PushPinSlashIcon = decorative(PushPinSlashGlyph, "PushPinSlashIcon");
export const QuestionIcon = decorative(QuestionGlyph, "QuestionIcon");
export const ShieldCheckIcon = decorative(ShieldCheckGlyph, "ShieldCheckIcon");
export const ShuffleIcon = decorative(ShuffleGlyph, "ShuffleIcon");
export const SignOutIcon = decorative(SignOutGlyph, "SignOutIcon");
export const SlidersHorizontalIcon = decorative(SlidersHorizontalGlyph, "SlidersHorizontalIcon");
export const SquareIcon = decorative(SquareGlyph, "SquareIcon");
export const SquaresFourIcon = decorative(SquaresFourGlyph, "SquaresFourIcon");
export const StackIcon = decorative(StackGlyph, "StackIcon");
export const SunIcon = decorative(SunGlyph, "SunIcon");
export const TargetIcon = decorative(TargetGlyph, "TargetIcon");
export const TrashIcon = decorative(TrashGlyph, "TrashIcon");
export const UploadSimpleIcon = decorative(UploadSimpleGlyph, "UploadSimpleIcon");
export const UserIcon = decorative(UserGlyph, "UserIcon");
export const UsersIcon = decorative(UsersGlyph, "UsersIcon");
export const WarningIcon = decorative(WarningGlyph, "WarningIcon");
export const XIcon = decorative(XGlyph, "XIcon");
export const XCircleIcon = decorative(XCircleGlyph, "XCircleIcon");
export const ArticleIcon = decorative(ArticleGlyph, "ArticleIcon");
export const CalendarPlusIcon = decorative(CalendarPlusGlyph, "CalendarPlusIcon");
export const ClipboardTextIcon = decorative(ClipboardTextGlyph, "ClipboardTextIcon");
export const ExamIcon = decorative(ExamGlyph, "ExamIcon");
export const ListMagnifyingGlassIcon = decorative(ListMagnifyingGlassGlyph, "ListMagnifyingGlassIcon");
export const QuotesIcon = decorative(QuotesGlyph, "QuotesIcon");
export const StudentIcon = decorative(StudentGlyph, "StudentIcon");
